import Head from "next/head";
import { MapLayout } from "../layouts/mapLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Google Map Api</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MapLayout />
    </>
  );
}
