import Head from "next/head";
import { Inter } from "@next/font/google";
import { MapLayout } from "@/layouts/mapLayout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Google Maps Api</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MapLayout />
      </main>
    </>
  );
}
